[project]
name = "crewai-learning"
version = "0.1.0"
description = "Repository for learning crewai"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai-tools>=0.14.0",
    "crewai>=0.83.0",
]
